run:
  name: Run batch updates
  description: Sequentially updates the provided update.* entities, halting on failure.
  fields:
    entities:
      description: List of update.* entity_ids to install.
      example:
        - update.esphome
        - update.hacs
    reboot_host:
      description: Reboot the host at the end (HA OS/Supervised). Otherwise restart core.
      example: false
    backup:
      description: Pass backup: true to update.install (when supported).
      example: true
